### ISSUE TITLE
ImportError: cannot import name 'decrypt' from 'Crypto'

### ISSUE THREAD

**Issue by Callump01** [themonomers/tesla#1]
Hi there,

Currently using TeslaToken.py (great work by the way!) to authenticate with the Tesla API, grab my token and use it elsewhere it an automated fashion. I'm currently getting the following error when attempting to run;

`ImportError: cannot import name 'decrypt' from 'Crypto'`

This is a fresh install of Python 3.9.5 and I've tried the PyCrypto, Crypto and Pycryptodom modules. What one are you specifically using here so that I can pip install?

Thanks.

**Comment by themonomers** [comment]
Hi!

Try installing cryptography:
$ pip install cryptography

Let me know if that works!  By the way these were written on Python 2.7.16 so some of the syntax might be off.

**Comment by Callump01** [comment]
Thanks for the very quick response. Getting the same error unfortunately... also downgraded to a fresh install of 2.7.16 just to rule that out.

Super weird because it shows under `pip list` just fine.

```
Package                  Version
------------------------ ---------
cachetools               3.1.1
certifi                  2021.5.30
cffi                     1.14.5
chardet                  4.0.0
configparser             4.0.2
cryptography             3.3.2  <------
enum34                   1.1.10
futures                  3.3.0
google-api-core          1.30.0
google-api-python-client 1.12.8
google-auth              1.30.2
google-auth-httplib2     0.1.0
google-auth-oauthlib     0.4.1
googleapis-common-protos 1.52.0
httplib2                 0.19.1
idna                     2.10
ipaddress                1.0.23
oauthlib                 3.1.0
packaging                20.9
pip                      18.1
protobuf                 3.17.3
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.20
pyparsing                2.4.7
pytz                     2021.1
requests                 2.25.1
requests-oauthlib        1.3.0
rsa                      4.5
sendEMail                1.0
setuptools               40.6.2
six                      1.16.0
uritemplate              3.0.1
urllib3                  1.26.5
```

**Comment by themonomers** [comment]
My cryptography shows as version 2.6.1.

Here's my entire pip list:
`Package                  Version  
------------------------ ---------
asn1crypto               0.24.0   
cachetools               3.1.1    
certifi                  2020.12.5
chardet                  4.0.0    
configparser             3.5.0b2  
cryptography             2.6.1    
entrypoints              0.3      
enum34                   1.1.6    
futures                  3.3.0    
google-api-core          1.26.2   
google-api-python-client 1.12.8   
google-auth              1.28.0   
google-auth-httplib2     0.1.0    
google-auth-oauthlib     0.4.1    
googleapis-common-protos 1.52.0   
httplib2                 0.19.0   
idna                     2.10     
influxdb                 5.3.1    
ipaddress                1.0.17   
keyring                  17.1.1   
keyrings.alt             3.1.1    
msgpack                  1.0.2    
oauthlib                 3.1.0    
packaging                20.9     
pip                      18.1     
protobuf                 3.15.6   
pyasn1                   0.4.8    
pyasn1-modules           0.2.8    
pycrypto                 2.6.1    
PyGObject                3.30.4   
pyparsing                2.4.7    
python-crontab           2.5.1    
python-dateutil          2.8.1    
pytz                     2021.1   
pyxdg                    0.25     
requests                 2.25.1   
requests-oauthlib        1.3.0    
RPi.GPIO                 0.7.0    
rsa                      4.5      
SecretStorage            2.3.1    
setuptools               40.8.0   
six                      1.15.0   
uritemplate              3.0.1    
urllib3                  1.26.4   
wheel                    0.32.3   
`

**Comment by themonomers** [comment]
Oh another thing, looking at the error message:  Did you also grab this file?  https://github.com/themonomers/tesla/blob/master/python/Crypto.py

**Comment by Callump01** [comment]
Redownloaded everything and gave it a run - hey presto!

Thanks so much for your quick help with this... incredibly useful scripts to have for my personal project.
